package-lock.json
package.json
src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/AiServiceDetailReview.jsx
src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailTip/AiServiceDetailTip.jsx
src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailTip/style.jsx
src/components/aiServiceDetail/aiServiceDetailIntro/style.jsx
src/pages/ai/AiServiceDetail.jsx
src/pages/ai/style.jsx

- PC 기준으로 AI Service 디테일 페이지 - 이용후기/이용꿀팁 탭 구현했습니다.
- 이용꿀팁 부분 디자인과 목록 보여주기 구현했습니다.
- 이용꿀팁 목록에 Paging 적용했습니다.

✨ Feat : AI Service 디테일 페이지 - 탭 구현 & 이용 꿀팁

---

src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailTip/AiServiceDetailTip.jsx

- AiServiceDetailTip 파일에서 import 경로 오류 수정했습니다

🐛 Fix: 경로 오류 수정

---

src/App.jsx
src/components/common/paging/ListView.jsx
src/components/common/paging/style.jsx
src/components/layouts/NavBar.jsx
src/components/layouts/style.jsx
src/components/main/mainAiList/MainAiServiceList.jsx
src/components/main/mainAiList/style.jsx
src/components/main/mainBanner/style.jsx
src/pages/main/style.jsx
src/style/globalStyle.js

:sparkles: Feat: sideBar

---

src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
src/components/common/aiServiceList/AiServiceList.jsx
src/components/common/paging/Paging.jsx
src/components/common/paging/style.css
src/components/common/paging/style.jsx
src/components/common/selector/Selector.jsx
src/pages/main/Main.jsx

-페이지네이션 수정
12345
678910
이렇게 선택 가능합니다.
- Seloctor에서 선택한 항목으로 Ai 정렬이 가능합니다.

✨ Feat: MainPage - pagination, selectorSort

---

src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailTip/AiServiceDetailTip.jsx

Detail Selector에 option 추가했습니다.

:sparkles: Feat: Detail Selector

---

src/pages/auths/authLogin/AuthLogin.jsx
src/pages/auths/authSignup/AuthSignup.jsx
src/pages/profile/Profile.jsx
src/pages/profile/profileChangePassword/ProfileChangePassword.jsx
src/pages/profile/profileMain/ProfileMain.jsx

:bug: Fix : 회원가입 오류 해결

---

src/components/common/paging/Paging.jsx
src/components/layouts/nabBar/NavBar.jsx
src/pages/main/Main.jsx

페이지 이동해도 위치는 그대로였던 버그를 수정했습니다.

:sparkles: 페이지 이동 시 제일 상단으로 이동

---

src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
src/components/aiServiceDetail/aiServiceDetailIntro/style.jsx

- 클립보드 아이콘이 아닌 다른 영역을 클릭했을 때, 링크가 복사되는 문제를 해결했습니다.

🐛 Fix: Ai Service 디테일 페이지 - 클립보드 영역 오류 해결

---

src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/AiServiceDetailReview.jsx
src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/CommentForm.jsx
src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/CommentList.jsx
src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Review.jsx
src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/style.jsx
src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
src/components/common/list/List.jsx
src/components/common/list/style.jsx
src/pages/ai/AiServiceDetail.jsx

- 이용후기 회원/비회원에 따른 별점 기능을 구현했습니다.
- 추가로 비회원인 경우에 따른 기능 비활성화를 구현했습니다.

✨ Feat : AI Service 디테일 페이지 - 이용후기 별점 구현

---

src/components/common/star/style.jsx
src/components/main/mainCategory/MainCategory.jsx
src/components/main/mainCategory/style copy.jsx
src/components/main/mainCategory/style.jsx
src/components/main/mainCategory/swiper.css
src/pages/main/Main.jsx

- 스크롤바로 이동가능
- 네비게이션 (<, >) 으로 이동가능
- 별점 회색 안 보이게 조절함

✨ Feat: 카테고리 선택 스와이퍼 추가, 별점 변경

---

package-lock.json
package.json
src/components/common/aiServiceList/AiService.jsx
src/components/layouts/nabBar/NavBar.jsx
src/components/layouts/nabBar/style.jsx
src/pages/auths/authLogin/AuthLogin.jsx
src/pages/community/communityCreatePost/CommunityCreatPost.jsx
src/pages/community/communityCreatePost/mdEditorStyle.css

✨ Feat: mdEditor 추가

---

src/components/common/list/List.jsx
src/components/common/list/style.jsx

- List 컴포넌트에 마우스 hover 효과 추가했습니다

💄 Style: List 컴포넌트 효과 추가

---

src/components/common/aiServiceList/AiService.jsx
src/pages/auths/authLogin/AuthLogin.jsx
src/pages/main/Main.jsx
src/pages/profile/profileChangePassword/ProfileChangePassword.jsx
src/pages/profile/profileMain/ProfileMain.jsx

✨ Feat: 연동 테스트

---

src/components/common/aiServiceList/AiService.jsx
src/components/common/aiServiceList/AiServiceList.jsx
src/components/common/paging/ListView.jsx
src/components/common/paging/Paging.jsx
src/pages/main/Main.jsx

:sparkles: Feat: Pagination api

---

src/components/common/aiServiceList/AiService.jsx
src/components/common/aiServiceList/style.jsx

:sparkles: Feat: MainPage nowrap

---

src/components/common/aiServiceList/AiService.jsx
src/components/common/aiServiceList/AiServiceList.jsx
src/components/common/highLightItem/HighLightItem.jsx
src/components/common/highLightItem/style.jsx
src/pages/main/Main.jsx
src/pages/search/Search.jsx

- Api 연결했습니다.
- Hightlight로 검색한 검색어 하이라이트 처리했는데 별로면 뺄게요

✨ Feat: MainPage, SearchPage - Api 연결

---

netlify.toml

🚀Deploy : Front 8차 테스트

---

src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailTip/AiServiceDetailTip.jsx
src/components/common/commonList/CommonList.jsx
src/components/common/commonList/style.jsx
src/components/common/list/List.jsx
src/components/common/noticeList/NoticeList.jsx
src/components/common/suggestionList/SuggestionList.jsx
src/components/common/tipsList/TipsList.jsx
src/components/common/tipsList/style.jsx
src/components/community/communityCommon/CommunityCommon.jsx
src/components/community/communityQna/CommunityQna.jsx
src/components/community/communityTips/CommunityTips.jsx

커뮤니티 GET 완료
- 인공지능 꿀팁 GET은 아직 
남은 일 
공지사항, 건의사항 GET

🛠️ Connect: 1차 연동 

---

src/components/aiServiceDetail/aiServiceDescription/AiServiceDescription.jsx
src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Comment.jsx
src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/CommentList.jsx
src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Review.jsx
src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
src/components/aiServiceDetail/aiServiceDetailIntro/style.jsx
src/components/common/commonCommentList/CommonCommentList.jsx
src/pages/ai/AiServiceDetail.jsx

인공지능 서비스 디테일 GET 완료
- 인공지능 서비스 디테일 불러오기
- 인공지능 서비스 디테일 정보 불러오기
- 인공지능 서비스 디테일 댓글 목록 불러오기
- 인공지능 서비스 디테일 내 댓글 목록 불러오기(유저)

✨ Feat: 인공지능 서비스 디테일 불러오기 API 연동

---

src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailTip/AiServiceDetailTip.jsx
src/components/common/commonList/CommonList.jsx
src/components/common/commonList/style.jsx
src/components/common/list/List.jsx
src/components/common/list/style.jsx
src/components/common/noPage/NoPage.jsx
src/components/common/noticeList/NoticeList.jsx
src/components/common/noticeList/style.jsx
src/components/common/suggestionList/SuggestionList.jsx
src/components/common/suggestionList/style.jsx
src/components/common/tipsList/TipsList.jsx
src/components/common/tipsList/style.jsx
src/components/community/communityCommon/CommunityCommon.jsx
src/components/community/communityCommonPost/CommunityCommonPost.jsx
src/components/community/communityCommonPost/style.jsx
src/components/community/communityQna/CommunityQna.jsx
src/components/community/communityQnaPost/CommunityQnaPost.jsx
src/components/community/communityQnaPost/style.jsx
src/components/community/communityTips/CommunityTips.jsx
src/components/community/communityTipsPost/CommunityTipsPost.jsx
src/components/community/communityTipsPost/style.jsx
src/pages/ai/AiServiceDetail.jsx
src/pages/community/communityCreatePost/CommunityCreatPost.jsx
src/pages/notice/Notice.jsx
src/pages/suggestion/Suggestion.jsx

나머지 게시판 목록 불러오기와 페이지네이션, option 적용 완료 했습니다.
남은 작업은
마이페이지 게시글 목록 GET과, 
게시글 확인, 작성 삭제..입니다

✨ feat : 게시판 목록 불러오기

---

src/components/aiServiceDetail/aiServiceDescription/style.jsx
src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/AiServiceDetailReview.jsx
src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Comment.jsx
src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/CommentForm.jsx
src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/CommentList.jsx
src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Review.jsx
src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/style.jsx
src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
src/components/common/commonCommentList/CommonCommentList.jsx
src/components/common/editDelete/EditDelete.jsx
src/pages/ai/AiServiceDetail.jsx
src/pages/ai/style.jsx
src/pages/auths/authLogin/AuthLogin.jsx
src/pages/community/communityCreatePost/CommunityCreatPost.jsx

✨ feat : AI 디테일

---

index.html
src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/CommentList.jsx
src/pages/main/Main.jsx

✨  Feat: SEO최적화 1단계

---

src/components/main/mainBanner/style.jsx
src/pages/main/style.jsx
src/style/globalStyle.js

💄Style: 메인페이지 애니메이션, 폰트 적용

---

src/components/common/keyword/Keyword.jsx
src/components/layouts/footer/FooterBar.jsx
src/components/layouts/nabBar/NavBar.jsx
src/components/layouts/nabBar/style.jsx
src/components/main/mainCategory/mainCategorySwiper.css
src/pages/about/About.jsx

Footer NavBar 전반적으로 변경
KeywordColor 색 추가

💄 Style: Footer, KeywordColor

---

src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Comment.jsx
src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/style.jsx
src/components/common/modal/Modal.jsx
src/components/common/modal/style.jsx
src/pages/ai/AiServiceDetail.jsx
src/pages/profile/profileComment/ProfileComment.jsx
src/pages/profile/profileFavorite/ProfileFavorite.jsx
src/pages/profile/profileFavoritePost/ProfileFavoritePost.jsx
src/pages/profile/profileMain/ProfileMain.jsx
src/pages/profile/profilePost/ProfilePost.jsx

마이페이지 API 연동했습니다.
page 적용해야 하는지 확인 후 추후 수정 필요
- 본인 좋아요 한 ai 서비스 목록 조회
- 본인 좋아요 한 커뮤니티 게시물 목록 조회

✨ Feat: 마이페이지 API 연동

---

src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
src/components/common/commonList/CommonList.jsx
src/components/common/commonList/style.jsx
src/components/common/list/List.jsx
src/components/common/list/style.jsx
src/components/common/noticeBanner/NoticeBanner.jsx
src/components/common/noticeBanner/style.jsx
src/components/common/noticeList/NoticeList.jsx
src/components/common/noticeList/style.jsx
src/components/common/suggestionList/SuggestionList.jsx
src/components/common/suggestionList/style.jsx
src/components/common/tipsList/TipsList.jsx
src/components/common/tipsList/style.jsx
src/components/community/communityQna/CommunityQna.jsx
src/components/community/communityTips/CommunityTips.jsx
src/components/community/communtiyDetailPageType/style.jsx
src/pages/community/communityCreatePost/CommunityCreatPost.jsx
src/pages/community/communityCreatePost/style.jsx
src/pages/community/communityDetail/DetailPage.jsx
src/pages/suggestion/suggestionCreate/SuggestionCreate.jsx

✨Feat:최종 1차 수정

---

src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Comment.jsx
src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/CommentList.jsx
src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Review.jsx
src/components/common/commentInput/CommentInput.jsx
src/components/common/commentInput/style.jsx
src/components/common/commonCommentList/CommonCommentList.jsx
src/components/common/communityDetailContent/CommunityDetailContent.jsx
src/components/common/editDelete/EditDelete.jsx
src/components/common/noticeList/NoticeList.jsx
src/components/common/noticeList/style.jsx
src/components/common/suggestionList/SuggestionList.jsx
src/components/common/suggestionList/style.jsx
src/pages/community/communityDetail/DetailPage.jsx
src/pages/suggestion/suggestionDetail/SuggestionDetailPage.jsx

✨Feat: 댓글기능 

---

package-lock.json
package.json
src/components/auths/authContentBox/AuthContentBox.jsx
src/components/auths/authSocialButton/style.jsx
src/components/common/commonList/CommonList.jsx
src/components/common/communityDetailContent/CommunityDetailContent.jsx
src/components/common/tipsList/style.jsx
src/components/community/communtiyDetailPageType/CommuntiyDetailPageType.jsx
src/pages/auths/authLogin/AuthLogin.jsx
src/pages/auths/authLogin/kakaoAuth.jsx
src/pages/auths/authSignup/style.jsx
src/pages/community/communityCreatePost/CommunityCreatPost.jsx
src/pages/community/communityCreatePost/style.jsx
src/pages/community/communityDetail/DetailPage.jsx
src/pages/community/communityEdit/CommunityEdit.jsx
src/pages/community/communityEdit/style.jsx
src/pages/profile/profileMain/ProfileMain.jsx
src/pages/profile/profileMain/style.jsx
src/pages/profile/profileModify/ProfileModify.jsx
src/pages/suggestion/suggestionCreate/SuggestionCreate.jsx
src/pages/suggestion/suggestionCreate/style.jsx
src/pages/suggestion/suggestionDetail/SuggestionDetailPage.jsx
src/pages/suggestion/suggestionDetail/style.jsx

✨Feat: 게시글, 마이페이지 수정

---

src/components/aiServiceDetail/aiServiceDescription/AiServiceDescription.jsx
src/components/aiServiceDetail/aiServiceDescription/style.jsx
src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
src/components/aiServiceDetail/aiServiceDetailIntro/style.jsx
src/components/main/mainCategory/style.jsx
src/pages/ai/style.jsx
src/pages/main/style.jsx

💄 Style: AI Service Detail 반응형

---

src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/AiServiceDetailReview.jsx
src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/Comment.jsx
src/components/aiServiceDetail/aiServiceDetailComment/aiServiceDetailReview/style.jsx
src/components/aiServiceDetail/aiServiceDetailIntro/style.jsx
src/components/common/aiServiceList/style.jsx
src/components/common/commonCommentList/style.jsx

💄 Style: 반응형 

---

src/components/common/postList/PostList.jsx
src/components/common/postList/PostMonitorList.jsx
src/pages/about/About.jsx
src/pages/about/animation.css
src/pages/notice/Notice.jsx

:sparkles: Feat: about 애니메이션 속도 조절

---

src/pages/community/communityCreatePost/CommunityCreatPost.jsx

:sparkles: Feat: 글작성 수정

---

src/pages/auths/authReset/AuthReset.jsx
src/pages/auths/authReseting/AuthReseting.jsx
src/pages/auths/authReseting/style.jsx
src/router.jsx

:sparkles: Feat: 비밀번호 재설정 기능

---

src/components/common/postList/PostList.jsx
src/components/common/postList/style.jsx
src/pages/about/About.jsx

:bug: Fix: 경로수정

---

package-lock.json
package.json
src/components/common/communityDetailContent/CommunityDetailContent.jsx
src/components/common/noticeBanner/style.jsx
src/pages/community/communityCreatePost/CommunityCreatPost.jsx
src/pages/suggestion/suggestionCreate/SuggestionCreate.jsx

:sparkles: Feat: file drop down

---

src/App.jsx
src/components/aiServiceDetail/aiServiceDetailIntro/AiServiceDetailIntro.jsx
src/components/aiServiceDetail/aiServiceDetailIntro/style.jsx
src/components/common/postList/PostList.jsx
src/components/common/postList/style.jsx
src/components/layouts/nabBar/NavBar.jsx
src/pages/ai/style.jsx

💄 Style: 반응형

---

src/style/globalStyle.js

:lipstick: Style: MarkDown
